spring:
  h2:
    console:
      enabled: true


  jpa:
    generate-ddl: true
    open-in-view: false
    show-sql: true

  profiles:
    active: dev

security:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 604800000

#    spring.datasource.url=jdbc:h2:mem:testdb
#    spring.datasource.driverClassName=org.h2.Driver
#    spring.datasource.username=sa
#    spring.datasource.password=
#    spring.h2.console.enabled=false

server:
  port: 8080